### ISSUE TITLE
More contrast needed for navbar (can't read text)

### ISSUE THREAD

**Issue by adyork** [BCODMO/blog.bco-dmo.org#11]
It's really hard to read with that little contrast in the navbar:
![image](https://user-images.githubusercontent.com/9537357/93530123-0ad66280-f90b-11ea-82fe-779120333583.png)

Not sure where else this background and text combination is, but I know pre-navbar is an issue:
https://github.com/BCODMO/blog.bco-dmo.org/blob/c9f974f4b310caa476ef38fe5305d8c5a3e45711/assets/css/bco-dmo.css#L7409

I suggest making pre-navbar match the footer
.footer-bar {
    background: #0E2D40;
    padding: 1rem 0;
    color: #fff;
    overflow: hidden;
}

![image](https://user-images.githubusercontent.com/9537357/93531355-1460ca00-f90d-11ea-870c-779199794fc1.png)

navbar text is also more readable with  font-size: 1rem and font-weight not bold.

Quick fix @ashepherd or do you want me to PR a change to bco-dmo.css?

**Comment by DanieK** [comment]
wow- that is tough... I agree, Amber.

**Comment by ashepherd** [comment]
Yeah, I agree too. Why the heck did we agree to that color with E84? Let me mess around with it

**Comment by ashepherd** [comment]
Fixed in 775f8a3a306338896d3426e8a0375fad0751052c

E84 did not have that text linked, so it appears with the correct contrast on their version. https://netlify.bco-dmo.org/

**Comment by DanieK** [comment]
Even in the netlify site, the header/footer text look two different colors? I like  @adyork 's suggestion to match them (to the footer text color) - tho maybe nitpicky?

**Comment by ashepherd** [comment]
Ok, color matches now. Fixed in 66406b4aef3eb73fa10cd3363f7066f416b719e6

**Comment by adyork** [comment]
OK closing for now. I still think it would be nice to have the header match the footer (that black looks a bit weird for the rest of the color scheme).  But it is passable and you can read it, so closing.

**Comment by ashepherd** [comment]
latest release aligns the background colors for the pre-navbar and the footer to #0E2D40
