### ISSUE TITLE
Add commenting

### ISSUE THREAD

**Issue by ashepherd** [BCODMO/blog.bco-dmo.org#9]
Articles about comments on static blogs
- [ ] https://darekkay.com/blog/static-site-comments/

**Comment by ashepherd** [comment]
[Commento.io](https://commento.io/)  - A Go-based comments app that can be added to static blogs. It can be self-hosted using Docker to run the Go code + Postgres for storage of comments. Or we can pay and have someone manage it outselves. I think its cheaper and better for us to run ourselves. 
See: 
- [ ] https://docs.commento.io/installation/self-hosting/
    - [ ] https://docs.commento.io/installation/self-hosting/on-your-server/docker.html
    - [ ] https://docs.commento.io/configuration/frontend/
    - [ ] https://docs.commento.io/configuration/backend/
- [ ] https://makerbubble.com/installing-commento-with-docker-on-linux/
- [ ] https://docs.commento.io/installation/self-hosting/


Tested with Google login and works well. Setup a [BCO-DMO Blogs Project in Google Console](https://console.developers.google.com/apis/credentials?project=bco-dmo-blogs) to enable the client ID and secret. the Redirect URI needs to go to the Commento app at https://<where-commento-is-running>/api/oauth/google/callback

With comments in postgres, we can add those right into the knowledge graph and link people to their social media accounts.

**Comment by ashepherd** [comment]
@DanieK, I think it'd be nice to add comments to start a conversation with folks who want to engage us, but I feel like I want them to identify themselves. Here, we can enable login with Google, Twitter, Github, and some others. 

What do you think? Should we let people comment at our blog?

**Comment by DanieK** [comment]
Love it! The Commento example looks great!

**Comment by ashepherd** [comment]
Comments are up and running on Amazon Lightsail (instance=bco-dmo_blog_comments). Documented here: https://github.com/BCODMO/commento.bco-dmo.org
